import streamlit as st
from utils.streamlit_utils import apply_base_styles
from dotenv import load_dotenv
from connection import contract

# Your other imports...

st.set_page_config(page_title="Verify | Badge Integrity", layout="wide", initial_sidebar_state="collapsed")
apply_base_styles()

load_dotenv()

# Get URL query parameters
query_params = st.experimental_get_query_params()
print(query_params)
# Extract 'cert_id' parameter (hex string)
cert_id = query_params.get('cert_id', [None])[0]
ipfs_hash = query_params.get('ipfs_hash', [None])[0]

def render_page(cert_id,ipfs_hash):
    if cert_id and ipfs_hash:
        # Construct the URL to the certificate IPFS link
        redirect_url = f"https://plum-geographical-alpaca-624.mypinata.cloud/ipfs/{ipfs_hash}"

        st.markdown(
            f"""
            <div class="hero">
                <div class="eyebrow">Certificate Check</div>
                <h1>Verify credential authenticity.</h1>
                <p>Certificate ID: <span class="accent">{cert_id}</span></p>
            </div>
            """,
            unsafe_allow_html=True,
        )

        st.markdown('<div class="app-card">', unsafe_allow_html=True)
        st.markdown(
            f'<a class="pill" href="{redirect_url}" target="_blank">View Certificate PDF</a>',
            unsafe_allow_html=True,
        )
        st.write("")
        if st.button("Verify Certificate", use_container_width=True):
            if contract is None:
                st.error("Smart contract not configured. Check deployment and connection.")
                return
            result = contract.functions.isVerified(cert_id).call()
            if result:
                st.success("Certificate successfully validated.")
            else:
                st.error("Certificate not found on-chain.")
        st.markdown("</div>", unsafe_allow_html=True)
    else:
        st.markdown(
            """
            <div class="hero">
                <div class="eyebrow">Certificate Check</div>
                <h1>No certificate details found.</h1>
                <p>Use a link generated by the institute to open this page.</p>
            </div>
            """,
            unsafe_allow_html=True,
        )

# Render the page
render_page(cert_id,ipfs_hash)

# Link back to home (or another page)

# st.markdown(
#     """
#     <script>
#     window.location.href = "/";
#     </script>
#     """,
#     unsafe_allow_html=True
# )
